# docker-compose.override.dev.yml
# Para ambiente de desarrollo (CI/CD)
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DJANGO_DEBUG: "False"
      LOG_LEVEL: INFO
      LOG_ENVIRONMENT: development
      LOG_CONSOLE: "true"
      LOG_JSON: "true"
      LOG_FILE: "true"
      POSTGRES_ENABLED: "true"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  postgres:
    environment:
      POSTGRES_MAX_CONNECTIONS: 50
